### PR TITLE
SW-2401 / SW-2398 / SW-2399 Empty state updates

### PR DESCRIPTION
**Pull request by karthikbtf**
- show sorted plots that only have plants
- show map without polygons if site has no polygons
- show disabled plot dropdown when there are no plots

### CODE REVIEW

**Comment by constanzauanini** [comment]
I was testing on staging and I see that Number of Plants by Plot and Species chart is not changing when changing planting site

**Comment by karthikbtf** [comment]
> I was testing on staging and I see that Number of Plants by Plot and Species chart is not changing when changing planting site

because of this change?

**Comment by karthikbtf** [comment]
> > I was testing on staging and I see that Number of Plants by Plot and Species chart is not changing when changing planting site
> 
> because of this change?

looking

**Comment by karthikbtf** [comment]
> I was testing on staging and I see that Number of Plants by Plot and Species chart is not changing when changing planting site

fixed now

**Review by constanzauanini — APPROVED** [review]
Lgtm!

**Pull request merged**
