### PR TITLE
 SW-2629 Set id to all onChange() functions

### PR DESCRIPTION
**Pull request by karthikbtf**
This is to follow up on onChange signature change from `(id, value)` to just `(value)` - see https://github.com/terraware/web-components/pull/233

### CODE REVIEW

**Review by constanzauanini — APPROVED** [review]

**Review by charlie-tf — APPROVED** [review]
LGTM

**Review by constanzauanini — APPROVED** [review]

**Comment by karthikbtf** [comment]
I will get this in so @charlie-tf can rebase his PR

**Comment by karthikbtf** [comment]
@charlie-tf you should be good to rebase

**Comment by charlie-tf** [comment]
> @charlie-tf you should be good to rebase

Thanks, @karthikbtf !

**Pull request merged**
