### PR TITLE
Update material ui, styles, styled-engine-sc, and emotion styled

### PR DESCRIPTION
**Pull request by nickgraz**
@karthikbtf I think this solves all the wonky style dep issues. Let me know what you think. It works locally on my end, had to update a few things to get everything in sync. 

If this doesn't work, I will revert all the recent Material updates and kick the can down the road.

### CODE REVIEW

**Comment by nickgraz** [comment]
* **#2523** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2523?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nickgraz and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by karthikbtf** [comment]
> @karthikbtf I think this solves all the wonky style dep issues. Let me know what you think. It works locally on my end, had to update a few things to get everything in sync.
> 
> If this doesn't work, I will revert all the recent Material updates and kick the can down the road.

Thanks @nickgraz I tried this branch locally, works for me 👍  Thanks for fixing this!

**Review by karthikbtf — APPROVED** [review]
Good to go, we need to bump web-components again after that is merged.

**Comment by karthikbtf** [comment]
> > @karthikbtf I think this solves all the wonky style dep issues. Let me know what you think. It works locally on my end, had to update a few things to get everything in sync.
> > If this doesn't work, I will revert all the recent Material updates and kick the can down the road.
> 
> Thanks @nickgraz I tried this branch locally, works for me 👍 Thanks for fixing this!

Vercel looks good as well.

**Pull request merged**
