### PR TITLE
SW-5103 Remove 'Accelerator' feature flag and bake it in

### PR DESCRIPTION
**Pull request by nickgraz**
This feature flag was hiding the console and deliverables.

### CODE REVIEW

**Comment by nickgraz** [comment]
* **#2374** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2374?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nickgraz and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by karthikbtf — APPROVED** [review]
🎉

**Review by karthikbtf — COMMENTED** [review]
Do we need to remove `featureFlagAccelerator` from `useAccelerator`?

**Comment by karthikbtf** [comment]
> Do we need to remove `featureFlagAccelerator` from `useAccelerator`?

I am blind, please ignore.

**Pull request merged**
