### PR TITLE
Fix temporary rendering of a generic map in plants dashboard

### PR DESCRIPTION
**Pull request by karthikbtf**
- don't render until we have a selection

### CODE REVIEW

**Comment by karthikbtf** [comment]
@constanzauanini can you try this vercel and lmk?

**Review by constanzauanini — APPROVED** [review]
Excellent! 🎉

**Comment by karthikbtf** [comment]
> 

Thanks @constanzauanini guessing it worked :)

**Comment by constanzauanini** [comment]
> > 
> 
> Thanks @constanzauanini guessing it worked :)

Yes, worked perfectly !

**Pull request merged**
