### PR TITLE
SW-2751 Use 4px width on all scrollbars in web-app

### PR DESCRIPTION
**Pull request by karthikbtf**
- as per Hannah's request
- test in vercel
- also pick up scroll bar changes mentioned here https://terraformation.atlassian.net/browse/SW-2504 towards the end

### CODE REVIEW

**Review by constanzauanini — APPROVED** [review]

**Comment by constanzauanini** [comment]
@hannah-cai it's a little harder now to scroll, but not sure if this is a problem since I always use pad or mouse to scroll:

Before:
before


Now:
now

**Comment by hannah-cai** [comment]
> @hannah-cai it's a little harder for me to scroll now, but not sure if this is a problem since I always use pad or mouse to scroll:
> 
> Before: before [ before ](https://user-images.githubusercontent.com/5919083/213557365-f4b4e57f-b9bc-4f33-984b-7a7c2d1f0494.gif) [ ](https://user-images.githubusercontent.com/5919083/213557365-f4b4e57f-b9bc-4f33-984b-7a7c2d1f0494.gif)
> 
> Now: now [ now ](https://user-images.githubusercontent.com/5919083/213557395-db0eae02-8d4b-47b7-b7f1-5868d51e1ade.gif) [ ](https://user-images.githubusercontent.com/5919083/213557395-db0eae02-8d4b-47b7-b7f1-5868d51e1ade.gif)

hmm that's a good point, I always use a trackpad so I didn't think about that. maybe we push it for now and then see if we get any user feedback about it

**Comment by karthikbtf** [comment]
> > @hannah-cai it's a little harder for me to scroll now, but not sure if this is a problem since I always use pad or mouse to scroll:
> > Before: before
> >       
> >         [
> >           
> >             before
> >           
> >         ](https://user-images.githubusercontent.com/5919083/213557365-f4b4e57f-b9bc-4f33-984b-7a7c2d1f0494.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/5919083/213557365-f4b4e57f-b9bc-4f33-984b-7a7c2d1f0494.gif)
> >         
> >        [ before ](https://user-images.githubusercontent.com/5919083/213557365-f4b4e57f-b9bc-4f33-984b-7a7c2d1f0494.gif)
> >       
> >         [
> >           
> >             before
> >           
> >         ](https://user-images.githubusercontent.com/5919083/213557365-f4b4e57f-b9bc-4f33-984b-7a7c2d1f0494.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/5919083/213557365-f4b4e57f-b9bc-4f33-984b-7a7c2d1f0494.gif)
> >         
> >        [ ](https://user-images.githubusercontent.com/5919083/213557365-f4b4e57f-b9bc-4f33-984b-7a7c2d1f0494.gif)
> > Now: now
> >       
> >         [
> >           
> >             now
> >           
> >         ](https://user-images.githubusercontent.com/5919083/213557395-db0eae02-8d4b-47b7-b7f1-5868d51e1ade.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/5919083/213557395-db0eae02-8d4b-47b7-b7f1-5868d51e1ade.gif)
> >         
> >        [ now ](https://user-images.githubusercontent.com/5919083/213557395-db0eae02-8d4b-47b7-b7f1-5868d51e1ade.gif)
> >       
> >         [
> >           
> >             now
> >           
> >         ](https://user-images.githubusercontent.com/5919083/213557395-db0eae02-8d4b-47b7-b7f1-5868d51e1ade.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/5919083/213557395-db0eae02-8d4b-47b7-b7f1-5868d51e1ade.gif)
> >         
> >        [ ](https://user-images.githubusercontent.com/5919083/213557395-db0eae02-8d4b-47b7-b7f1-5868d51e1ade.gif)
> 
> hmm that's a good point, I always use a trackpad so I didn't think about that. maybe we push it for now and then see if we get any user feedback about it

sounds good 👍

**Comment by karthikbtf** [comment]
@hannah-cai did you check the left nav scroll bar cut-off fix as well?

**Comment by hannah-cai** [comment]
@karthikbtf the size change looks good! is the color change in a separate branch? (I'd made a jira task [here](https://terraformation.atlassian.net/browse/SW-2731?search_id=fd7fcefe-5caa-46c4-80e5-47acc0358761), maybe I should've tagged you since it seems like you missed it)

**Comment by hannah-cai** [comment]
> @hannah-cai did you check the left nav scroll bar cut-off fix as well?

it looks good as well! :)

**Comment by karthikbtf** [comment]
> @karthikbtf the size change looks good! is the color change in a separate branch? (I'd made a jira task [here](https://terraformation.atlassian.net/browse/SW-2731?search_id=fd7fcefe-5caa-46c4-80e5-47acc0358761), maybe I should've tagged you since it seems like you missed it)

ugh, yes i wasn't aware of that jira.. let me see if i can get that in here, it's a change in web-components.

**Comment by karthikbtf** [comment]
> > @karthikbtf the size change looks good! is the color change in a separate branch? (I'd made a jira task [here](https://terraformation.atlassian.net/browse/SW-2731?search_id=fd7fcefe-5caa-46c4-80e5-47acc0358761), maybe I should've tagged you since it seems like you missed it)
> 
> ugh, yes i wasn't aware of that jira.. let me see if i can get that in here, it's a change in web-components.

can you approve this one? https://github.com/terraware/web-components/pull/260
once that lands, i will update the current PR with the updated web-components version

**Comment by karthikbtf** [comment]
> > > @karthikbtf the size change looks good! is the color change in a separate branch? (I'd made a jira task [here](https://terraformation.atlassian.net/browse/SW-2731?search_id=fd7fcefe-5caa-46c4-80e5-47acc0358761), maybe I should've tagged you since it seems like you missed it)
> > 
> > 
> > ugh, yes i wasn't aware of that jira.. let me see if i can get that in here, it's a change in web-components.
> 
> can you approve this one? [terraware/web-components#260](https://github.com/terraware/web-components/pull/260) once that lands, i will update the current PR with the updated web-components version

Ok, the color fix has been applied. Will get this in for now, if anything need further updates - will do that separate from this PR.

**Pull request merged**
