### PR TITLE
SW-2710 Update Cypress session for Spring Boot 3

### PR DESCRIPTION
**Pull request by sgrimm**
When terraware-server is upgraded to Spring Boot 3, the canned login session data
used by the Cypress tests will stop working because there have been changes to
the Spring session classes. Use a serialized Spring Boot 3 session object instead.

### CODE REVIEW

**Comment by sgrimm** [comment]
Cypress tests in CI are expected to fail on this one until https://github.com/terraware/terraware-server/pull/1251 is merged.

**Comment by sgrimm** [comment]
@charlie-tf @constanzauanini Server changes are merged, so this is ready to review (not that there's much to "review" here other than that the tests pass).

**Review by constanzauanini — APPROVED** [review]
Tests passing!

**Review by charlie-tf — APPROVED** [review]
👍

**Pull request merged**
