### PR TITLE
Add/Edit Person Form

### PR DESCRIPTION
**Pull request by charlie-tf**
image
image
image
image
image
image

### CODE REVIEW

**Review by karthikbtf — APPROVED** [review]
lgtm 🎉 
btw this selected color legit?
Terraware App 2022-11-29 15-18-16

**Comment by charlie-tf** [comment]
> lgtm 🎉 btw this selected color legit?

Good question. @hannah-cai what should this color be if not?

**Comment by hannah-cai** [comment]
> > lgtm 🎉 btw this selected color legit?
> 
> Good question. @hannah-cai what should this color be if not?

yes, this color is correct!

**Comment by hannah-cai** [comment]
not sure what's causing such a big gap between the rows of fields, the padding between them should be 16px
image

also, noticed that clicking on disabled fields leads to some funky behavior (not directly related to this branch though)
https://user-images.githubusercontent.com/45954862/204671521-6676f91e-8e4f-48c2-916e-6656945aad4b.mov

otherwise everything looks good! :)

**Comment by charlie-tf** [comment]
>not sure what's causing such a big gap between the rows of fields, the padding between them should be 16px

@hannah-cai, do you mean this should be 16px?
image


>clicking on disabled fields leads to some funky behavior

Hm, yeah, goofy. I'll take a look after this.

**Comment by hannah-cai** [comment]
> > not sure what's causing such a big gap between the rows of fields, the padding between them should be 16px
> 
> @hannah-cai, do you mean this should be 16px? image
> 
> > clicking on disabled fields leads to some funky behavior
> 
> Hm, yeah, goofy. I'll take a look after this.

I meant the vertical spacing! like above "select a role for this person"

**Review by joshbuchea — APPROVED** [review]

**Comment by charlie-tf** [comment]
> I meant the vertical spacing! like above "select a role for this person"

Ooh, gotcha 👍

**Comment by charlie-tf** [comment]
@hannah-cai Let me know if the spacing looks better. I updated to better match the Figma.

**Comment by hannah-cai** [comment]
> @hannah-cai Let me know if the spacing looks better. I updated to better match the Figma.

@charlie-tf I didn't realize, but the spacing in the spec was wrong in Figma 😭 but now that I'm looking at it, I think this was an interim solution when we didn't have tooltips yet. I'll ask the design team if we want to just switch this description to a tooltip and then get back to you

**Comment by charlie-tf** [comment]
@hannah-cai I updated the spacing again to match the figma. On the question of tooltip: do you mind if I merge this now and followup with whatever you decide for switching to a tooltip or not?

**Comment by hannah-cai** [comment]
> @hannah-cai I updated the spacing again to match the figma. On the question of tooltip: do you mind if I merge this now and followup with whatever you decide for switching to a tooltip or not?

thanks for doing that! and sure—for context we did decide to do a tooltip, and Rachel will be making screens for how it should look; not sure if she's done yet.

**Pull request merged**
