### PR TITLE
SW-2076 Add PageHeaderWrapper to Pages

### PR DESCRIPTION
**Pull request by charlie-tf**
- Added the header wrapper to several more pages:
  - species list
  - accessions list
  - check-in accessions
  - monitoring
  - inventory list
- rearrange accessions mobile view to have cta buttons in header

### CODE REVIEW

**Review by karthikbtf — COMMENTED** [review]
Spiffy!! The peek-a-boo scrolling works on all the targeted pages, desktop and mobile.
Very cool!

Two observed issues:
1) empty state for monitoring is no longer centered
2) scroll state is preserved across People and SeedBanks (not sure why this is affected as we didn't target these but maybe some unrelated change got picked up?)

**Comment by charlie-tf** [comment]
> Spiffy!! The peek-a-boo scrolling works on all the targeted pages, desktop and mobile. Very cool!
> 
> Two observed issues:
> 
> 1. empty state for monitoring is no longer centered
> 2. scroll state is preserved across People and SeedBanks (not sure why this is affected as we didn't target these but maybe some unrelated change got picked up?)

1. Fixed by wrapping that content in a Container instead of a div
2. This appears to be happening in prod, so not related to these changes, but worth checking out.

**Review by constanzauanini — APPROVED** [review]
Lgtm! One question, on accession page, are we sure we want the checkin message to be part of the pageHeader ?

**Comment by charlie-tf** [comment]
> Lgtm! One question, on accession page, are we sure we want the checkin message to be part of the pageHeader ?

I believe so yes, from the figma:
>If there’s a page message, it will be part of the sticky header (below the heading and actions). Page messages will now be full-width.

**Comment by constanzauanini** [comment]
> Member

Ok, I'm not sure if the check in message is a normal page message, but lets keep it like this. If @chudo76 has a comment, we can change it later

**Pull request merged**
