### PR TITLE
SW-1553 Remove all references to primary/secondary collectors in FE code

### PR DESCRIPTION
**Pull request by karthikbtf**
- update generated api schema

### CODE REVIEW

**Comment by karthikbtf** [comment]
This is not urgent - just keeping it ready for when the time comes.

**Review by sgrimm — APPROVED** [review]
You generated the schema by pulling https://github.com/terraware/terraware-server/pull/582 locally, I assume? Either way, this looks good.

**Comment by karthikbtf** [comment]
> You generated the schema by pulling [terraware/terraware-server#582](https://github.com/terraware/terraware-server/pull/582) locally, I assume? Either way, this looks good.

Yes I pulled your branch. Let me try doing this off main in case I missed something.

**Comment by karthikbtf** [comment]
> > You generated the schema by pulling [terraware/terraware-server#582](https://github.com/terraware/terraware-server/pull/582) locally, I assume? Either way, this looks good.
> 
> Yes I pulled your branch. Let me try doing this off main in case I missed something.

Looks good after regenerating off main.

**Comment by karthikbtf** [comment]
@constanzauanini just fyi I will do something similar for FE. 
Our cypress runs are expensive, if we have a newer commit on a dev branch we should cancel previous builds.

**Comment by karthikbtf** [comment]
> @constanzauanini just fyi I will do something similar for FE. Our cypress runs are expensive, if we have a newer commit on a dev branch we should cancel previous builds.

oops, wrong PR

**Pull request merged**
