### PR TITLE
SW-2264 Species Table Updates

### PR DESCRIPTION
**Pull request by charlie-tf**
image
image

### CODE REVIEW

**Review by karthikbtf — APPROVED** [review]

**Comment by hannah-cai** [comment]
look good! my only comment is that the "clear" icon (x) in the search bar should be 16px instead of 24.
image

**Comment by charlie-tf** [comment]
> look good! my only comment is that the "clear" icon (x) in the search bar should be 16px instead of 24. image

@hannah-cai We have set both the `TextField` left and right icons to equal the default line height, 24px. Is that something that should change to 16px app-wide for `TextField`s? They also have a default font-size of 16px.

**Comment by hannah-cai** [comment]
> > look good! my only comment is that the "clear" icon (x) in the search bar should be 16px instead of 24. image
> 
> @hannah-cai We have set both the `TextField` left and right icons to equal the default line height, 24px. Is that something that should change to 16px app-wide for `TextField`s? They also have a default font-size of 16px.

I don't think so, when there's a search icon or other icon it should still be 24px. it's just the clear icon that should be smaller

**Comment by charlie-tf** [comment]
> I don't think so, when there's a search icon or other icon it should still be 24px. it's just the clear icon that should be smaller

Okay, I can work with that

**Comment by hannah-cai** [comment]
> > I don't think so, when there's a search icon or other icon it should still be 24px. it's just the clear icon that should be smaller
> 
> Okay, I can work with that

it looks smaller than 16 right now, I think the padding-right is scaling it to be smaller. the info icons on the table are at 16px for reference

**Comment by charlie-tf** [comment]
> > > I don't think so, when there's a search icon or other icon it should still be 24px. it's just the clear icon that should be smaller
> > 
> > 
> > Okay, I can work with that
> 
> it looks smaller than 16 right now, I think the padding-right is scaling it to be smaller. the info icons on the table are at 16px for reference

dang, you are right. I should have done margin-right instead 😓 I'll fix it and put it up to review again when that's done

**Comment by charlie-tf** [comment]
yayy
image

**Pull request merged**
