### PR TITLE
SW-5538: Table column sorting for Species table for Species List Deliverable doesn't seem to work

### PR DESCRIPTION
**Pull request by joshbuchea**
This PR includes changes to resolve an issue that was causing table sorting to not working in the species deliverable table.

### CODE REVIEW

**Comment by nickgraz** [comment]
Is this all needed only because of the fact that the column name is a nested property? Or are there other reasons?

**Comment by joshbuchea** [comment]
@nickgraz changes were made because of the nested property, no other reasons

**Comment by nickgraz** [comment]
> @nickgraz changes were made because of the nested property, no other reasons

This can be solved by transforming the data into a flat structure.

**Comment by joshbuchea** [comment]
It's also solved in this PR, I'm not sure it'd be worth spending more time to change this now.

**Comment by nickgraz** [comment]
> It's also solved in this PR, I'm not sure it'd be worth spending more time to change this now.

If you are introducing more static functions then you should add unit tests for them. In my opinion this is being solved "the hard way" and is introducing more complexity when it is unnecessary. At a minimum, if you want to do it this way, there should be unit tests and you should try to avoid using the `any` type.

**Comment by joshbuchea** [comment]
I assumed the data was structured with nested properties for a reason. I don't agree that it's adding much complexity and think it's fine to do it this way.

**Comment by nickgraz** [comment]
> I assumed the data was structured with nested properties for a reason. I don't agree that it's adding much complexity and think it's fine to do it this way.

We have divergent opinions on complexity. No problem. If you must do it this way, can you at least write some unit tests for the static utility functions you've created and remove the `any` type?

**Comment by nickgraz** [comment]
[Here](https://github.com/terraware/terraware-web/pull/2785) is the way I was thinking it would be solved. Either way, I am OK with your approach if some tests are added and the `any` type is removed.

**Comment by joshbuchea** [comment]
I don't have a strong preference for how the fix is implemented, so I'm happy to close this PR in favor of yours.

**Comment by joshbuchea** [comment]
FWIW, I just disagreed with the notion that a change was necessary and didn't want to invest more time on this issue.

**Comment by joshbuchea** [comment]
Closing in favor of #2785

**Pull request closed without merging**
