### PR TITLE
Updated translations from Phrase

### PR DESCRIPTION
**Pull request by terraware-phrase**
Exported the most recent locale files from Phrase

### CODE REVIEW

**Review by charlie-tf — APPROVED** [review]
Looks good in vercel—language selection is working with these changes

**Review by karthikbtf — APPROVED** [review]

**Comment by karthikbtf** [comment]
They weren't kidding about the conflicts, will take a look locally.

**Comment by karthikbtf** [comment]
> They weren't kidding about the conflicts, will take a look locally.

Ok I believe the conflicts are resolved now.

**Comment by charlie-tf** [comment]
> > They weren't kidding about the conflicts, will take a look locally.
> 
> Ok I believe the conflicts are resolved now.

Wow, thanks Karthik!

**Pull request merged**
