### PR TITLE
SW-2267 reduce # of fetches to BE for accession, in accession view

### PR DESCRIPTION
**Pull request by karthikbtf**
- use react state for snackbar - since it was used as a dependency in useEffect, which was being triggered more often than desired
- reduced fetches from 10 to 2

### CODE REVIEW

**Comment by karthikbtf** [comment]
probably need to check if other places need similar changes

**Review by charlie-tf — APPROVED** [review]
Oh interesting. So `snackbar` was getting mutated multiple times, triggering that `useEffect`?

**Comment by constanzauanini** [comment]
> > Oh interesting. So `snackbar` was getting mutated multiple times, triggering that `useEffect`?
> 
> Since it wasn't in the react state - every re-render was creating a new snackbar object - which is a dependency in a useCallback function that fetches the accession (and uses snackbar to show error messages). The useCallback function is a dependency in a useEffect - which calls the useCallback to initialize the accession. Moved that into a react state and noticed way fewer calls. Why this generated that many calls I don't know, wondering if React calls the useCallback/useEffect functions for every change in the dependencies list instead of an optimized call after all dependencies have changed.

Oh, thanks for fixing this Karthik

**Comment by karthikbtf** [comment]
> > > Oh interesting. So `snackbar` was getting mutated multiple times, triggering that `useEffect`?
> > 
> > 
> > Since it wasn't in the react state - every re-render was creating a new snackbar object - which is a dependency in a useCallback function that fetches the accession (and uses snackbar to show error messages). The useCallback function is a dependency in a useEffect - which calls the useCallback to initialize the accession. Moved that into a react state and noticed way fewer calls. Why this generated that many calls I don't know, wondering if React calls the useCallback/useEffect functions for every change in the dependencies list instead of an optimized call after all dependencies have changed.
> 
> Oh, thanks for fixing this Karthik

I think we may have this happening in other places, I know that I added snackbar in many components. Will do a scan of all components later.

**Pull request merged**
