### PR TITLE
SW-2907 Don't allow non-numeric entries for quantities in nursery withdrawal form

### PR DESCRIPTION
**Pull request by constanzauanini**

### CODE REVIEW

**Review by charlie-tf — APPROVED** [review]
LGTM!

**Review by karthikbtf — COMMENTED** [review]
batch details form may need some clean up as well? 
also maybe remove all the numeric parsing code where it's no longer necessary?
also may want to check on plans for i18n.. not sure if we want user to be able to enter ',' etc.. but maybe as a follow up

**Comment by karthikbtf** [comment]
> batch details form may need some clean up as well? also maybe remove all the numeric parsing code where it's no longer necessary? also may want to check on plans for i18n.. not sure if we want user to be able to enter ',' etc.. but maybe as a follow up

Please refer to this PR https://github.com/terraware/terraware-web/pull/1159 to see related changes I had done last week, in case it helps with the cleanup.

**Comment by constanzauanini** [comment]
> batch details form may need some clean up as well? also maybe remove all the numeric parsing code where it's no longer necessary? also may want to check on plans for i18n.. not sure if we want user to be able to enter ',' etc.. but maybe as a follow up

Batch details quantity form is correct. I checked and fields are type number. We still need format code here for the total quantity and withdraw quantity because we calculate in the FE but we want to show formatted.

**Comment by karthikbtf** [comment]
> > batch details form may need some clean up as well? also maybe remove all the numeric parsing code where it's no longer necessary? also may want to check on plans for i18n.. not sure if we want user to be able to enter ',' etc.. but maybe as a follow up
> 
> Batch details quantity form is correct. I checked and fields are type number. We still need format code here for the total quantity and withdraw quantity because we calculate in the FE but we want to show formatted.

I made those formatting changes in the PR I linked above. Also added code to 'parse' numbers from strings, since we are changing the input to number, you may need to cleanup some of that parsing code.

**Comment by constanzauanini** [comment]
> > > > batch details form may need some clean up as well? also maybe remove all the numeric parsing code where it's no longer necessary? also may want to check on plans for i18n.. not sure if we want user to be able to enter ',' etc.. but maybe as a follow up
> > > 
> > > 
> > > Batch details quantity form is correct. I checked and fields are type number. We still need format code here for the total quantity and withdraw quantity because we calculate in the FE but we want to show formatted.
> > 
> > 
> > I made those formatting changes in the PR I linked above. Also added code to 'parse' numbers from strings, since we are changing the input to number, you may need to cleanup some of that parsing code.
> 
> i think it's on line 420

Oh, I see now. Thank you!

**Review by karthikbtf — APPROVED** [review]
looks good, one suggestion remove some of the unwanted parsing code..
also we may end up backtracking all this if PMs want localized number support within the inputs.. let's see

**Comment by constanzauanini** [comment]
> > > > > > batch details form may need some clean up as well? also maybe remove all the numeric parsing code where it's no longer necessary? also may want to check on plans for i18n.. not sure if we want user to be able to enter ',' etc.. but maybe as a follow up
> > > > > 
> > > > > 
> > > > > Batch details quantity form is correct. I checked and fields are type number. We still need format code here for the total quantity and withdraw quantity because we calculate in the FE but we want to show formatted.
> > > > 
> > > > 
> > > > I made those formatting changes in the PR I linked above. Also added code to 'parse' numbers from strings, since we are changing the input to number, you may need to cleanup some of that parsing code.
> > > 
> > > 
> > > i think it's on line 420
> > 
> > 
> > Oh, I see now. Thank you!
> 
> I just checked, the seedlings batch details numbers are all text. I had added parsing there too. Do we need to change those to numbers?

I thought you were talking about the batches quantity form. Yes, it's better if they are numbers. Will update

**Comment by karthikbtf** [comment]
> > > > > > > batch details form may need some clean up as well? also maybe remove all the numeric parsing code where it's no longer necessary? also may want to check on plans for i18n.. not sure if we want user to be able to enter ',' etc.. but maybe as a follow up
> > > > > > 
> > > > > > 
> > > > > > Batch details quantity form is correct. I checked and fields are type number. We still need format code here for the total quantity and withdraw quantity because we calculate in the FE but we want to show formatted.
> > > > > 
> > > > > 
> > > > > I made those formatting changes in the PR I linked above. Also added code to 'parse' numbers from strings, since we are changing the input to number, you may need to cleanup some of that parsing code.
> > > > 
> > > > 
> > > > i think it's on line 420
> > > 
> > > 
> > > Oh, I see now. Thank you!
> > 
> > 
> > I just checked, the seedlings batch details numbers are all text. I had added parsing there too. Do we need to change those to numbers?
> 
> I thought you were talking about the batches quantity form. Yes, it's better if they are numbers. Will update

Thanks Constanza. Yes batches is already number.. I think if we update the details modal we will be using numbers across inventory flows which will be consistent 🙏

**Review by karthikbtf — APPROVED** [review]
Thank you so much!!

**Pull request merged**
