### PR TITLE
SW-4617 Remove the query param and sub location filtering within the inventory list of batches

### PR DESCRIPTION
**Pull request by nickgraz**
- The query param logic is baked into the InventoryTable (in a later PR) for all filters.
- The sub location scrubbing is baked into the Search component (in a later PR) which is where facilities are being populated and selected.

### CODE REVIEW

**Comment by nickgraz** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/1968?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1965** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/1965?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1966** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/1966?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #1967** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/1967?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #1968** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/1968?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-web/1968?utm_source=stack-comment).

**Review by karthikbtf — COMMENTED** [review]
looks good but requires a rebase perhaps.. there was a storybook failure as well, could be transient

**Comment by nickgraz** [comment]
Trying out another build

**Comment by nickgraz** [comment]
@karthikbtf  👀

**Review by karthikbtf — APPROVED** [review]
👍

**Comment by nickgraz** [comment]
### Merge activity

* **Jan 3, 3:04 PM**: @nickgraz started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-web/1968).

**Pull request merged**
