### PR TITLE
SW-3182 Add `%` to Mortality Rate Fields

### PR DESCRIPTION
**Pull request by charlie-tf**
image
image

### CODE REVIEW

**Review by karthikbtf — APPROVED** [review]

**Comment by karthikbtf** [comment]
There might be a problem running the backend in the deployment.

**Comment by charlie-tf** [comment]
Oops, I did this wrong: 
image
Looking into fixing it

**Comment by karthikbtf** [comment]
> Oops, I did this wrong: image Looking into fixing it

Changes look good...

**Comment by charlie-tf** [comment]
Trying a newer version of postgres. In testing locally, I was finding that postgres 12 did not like a line in my migration,
``` sql
ALTER VIEW nursery.withdrawal_summaries RENAME plot_names TO planting_subzone_names;
```
and crashing the service, although when I was developing the line was accepted fine by the backend. The backend is on postgres 13, which may explain the difference. Trying that out in the CI here to see if it helps.

**Comment by charlie-tf** [comment]
Yes, that fixed it.

**Comment by charlie-tf** [comment]
@karthikbtf please take a look at this change when you get a chance. Thank you

**Comment by karthikbtf** [comment]
> @karthikbtf please take a look at this change when you get a chance. Thank you

The version upgrade looks good 👍

**Pull request merged**
