### PR TITLE
SW-4415 Show planting seasons in site details

### PR DESCRIPTION
**Pull request by sgrimm**
Detailed planting sites can have a list of planting seasons. Display the list on
the details page.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #1915** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/1915?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1916** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/1916?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
      * **PR #1917** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/1917?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-web/1916?utm_source=stack-comment).

**Comment by sgrimm** [comment]
Screenshot 2023-12-15 at 10 30 41 AM

**Review by nickgraz — APPROVED** [review]
Looks good

**Comment by sgrimm** [comment]
### Merge activity

* **Dec 15, 2:55 PM**: @@sgrimm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-web/1916).

**Pull request merged**
