### PR TITLE
SW-2251: Update NavBar for nested hierarchy navigation

### PR DESCRIPTION
**Pull request by joshbuchea**
This PR updates the navigation to use a nested hierarchy, viewable [here in the designs](https://www.figma.com/file/DftqOeGx8irCdRf7IZ4lbc/Navigation?node-id=5005%3A199381&viewport=-688%2C-4385%2C0.64).

#### Mobile

tree-location-gy2aw7plr-terraformation vercel app_inventory(iPhone SE)

tree-location-gy2aw7plr-terraformation vercel app_inventory(iPhone SE) (1)

tree-location-gy2aw7plr-terraformation vercel app_inventory(iPhone SE) (3)

#### Desktop

Screen Shot 2022-11-15 at 12 11 55 PM

Screen Shot 2022-11-15 at 12 11 59 PM

Screen Shot 2022-11-15 at 12 12 02 PM

### BEFORE

Screen Shot 2022-11-15 at 12 11 47 PM

### CODE REVIEW

**Review by charlie-tf — APPROVED** [review]
pretty straightforward 👍

**Comment by hannah-cai** [comment]
it looks good! a few comments:
- I think I've mentioned this before, but all nav elements (including the top nav) should have mix-blend-mode multiply applied
- nav items should have 16px border radius instead of 32px
- all sub-navigation shouldn't have an icon (there are currently icons for the ones under locations) and the the text should have 40px left padding (I updated this in the spec, so that the text aligns with main navigation)
image
- the location icon should be updated to the one in the image above (I'd forgotten to update that in the spec earlier, that's my bad)
- currently, the caret disappears when dropdowns are open. I think that we should still show them, like [this](https://www.figma.com/file/DftqOeGx8irCdRf7IZ4lbc/Navigation?node-id=4914%3A171226&viewport=300%2C280%2C0.31&t=07zs8VjirH46ZaWI-11). I think we should also keep the hover state, even though if you click it it won't do anything

**Comment by joshbuchea** [comment]
@hannah-cai thanks for the feedback 🙌 I'll remove the icons from the nested nav items in this PR, and will fix other style related issues in the components in the `web-components` repo.

**Comment by joshbuchea** [comment]
@hannah-cai I've been referencing [these designs](https://www.figma.com/file/DftqOeGx8irCdRf7IZ4lbc/Navigation?node-id=4825%3A150576&viewport=-688%2C-4385%2C0.64&t=G75d2Ix4wUByW1Q9-0), but they still show `32px` left padding for nested nav items.

Could you please confirm all specs are up to date in this file, thanks 🙏

**Comment by hannah-cai** [comment]
> @hannah-cai I've been referencing [these designs](https://www.figma.com/file/DftqOeGx8irCdRf7IZ4lbc/Navigation?node-id=4825%3A150576&viewport=-688%2C-4385%2C0.64&t=G75d2Ix4wUByW1Q9-0), but they still show `32px` left padding for nested nav items.
> 
> Could you please confirm all specs are up to date in this file, thanks 🙏

just updated those specs! thanks for calling that out.

**Comment by hannah-cai** [comment]
another detail I missed earlier—nav items should have 12px top and bottom padding, not 16.

**Pull request merged**
