### PR TITLE
SW-5596 Deliverables List in PartEx: Address issues with Project dropdown behavior

### PR DESCRIPTION
**Pull request by constanzauanini**
Make project dropdown a selector instead of a filter.
For single-Project Participants, the Project is automatically selected.
Change the “No Project” value text to “All”.

### CODE REVIEW

**Review by nickgraz — COMMENTED** [review]
It seems the best way to do this is to allow the consumer to pass in the "no project" filter label. The functionality seems identical (aside from the auto selection if there's only one project).

**Comment by constanzauanini** [comment]
> It seems the best way to do this is to allow the consumer to pass in the "no project" filter label. The functionality seems identical (aside from the auto selection if there's only one project).

I'm also keeping the selected project to the other pages (modules, home, etc) with this change. Do you think that is not needed? I used the same selector as in home and modules page

**Comment by nickgraz** [comment]
> > It seems the best way to do this is to allow the consumer to pass in the "no project" filter label. The functionality seems identical (aside from the auto selection if there's only one project).
> 
> I'm also keeping the selected project to the other pages (modules, home, etc) with this change. Do you think that is not needed? I used the same selector as in home and modules page

Oh OK I see. That makes sense. I guess I am still unsure why the entire dropdown is being rebuilt.

**Comment by alexTerraformation** [comment]
Not sure if it's related to any changes for this task, but I found today that none of the deliverables filters are working at all at the moment.  https://terraformation.atlassian.net/browse/SW-5865

**Comment by constanzauanini** [comment]
> Not sure if it's related to any changes for this task, but I found today that none of the deliverables filters are working at all at the moment. https://terraformation.atlassian.net/browse/SW-5865

They work on this branch, probably some change from staging. Will review

**Review by nickgraz — APPROVED** [review]

**Pull request merged**
