### PR TITLE
SW-3919 MyAccount language and preferred units selectors should be full width

### PR DESCRIPTION
**Pull request by constanzauanini**
Screenshot 2023-07-17 at 12 03 06

### CODE REVIEW

**Review by karthikbtf — APPROVED** [review]
Looks great thanks!
For mobile the inputs use up table width. Unrelated to this PR for sure.
Moving the Table out of the top level grid container should fix it.. small change but sure we can do this separately if preferred.
Also, do you think we should get Chudo's feedback?

**Comment by constanzauanini** [comment]
> Looks great thanks! For mobile the inputs use up table width. Unrelated to this PR for sure. Moving the Table out of the top level grid container should fix it.. small change but sure we can do this separately if preferred. Also, do you think we should get Chudo's feedback?

Oh, will fix that now. I think we can merge it when it's ready and if Chudo has any feedback we can follow up later

**Comment by constanzauanini** [comment]
> Looks great thanks! For mobile the inputs use up table width. Unrelated to this PR for sure. Moving the Table out of the top level grid container should fix it.. small change but sure we can do this separately if preferred. Also, do you think we should get Chudo's feedback?

Locally it looks good, that's strange

**Comment by karthikbtf** [comment]
> > Looks great thanks! For mobile the inputs use up table width. Unrelated to this PR for sure. Moving the Table out of the top level grid container should fix it.. small change but sure we can do this separately if preferred. Also, do you think we should get Chudo's feedback?
> 
> Locally it looks good, that's strange

Hmm.. yes for some reason broken in vercel. We can maybe just create a new ticket if you prefer.
Thanks so much for the changes. Yes we can follw up on any @chudo76 to give feedback later.

**Comment by constanzauanini** [comment]
> > > Looks great thanks! For mobile the inputs use up table width. Unrelated to this PR for sure. Moving the Table out of the top level grid container should fix it.. small change but sure we can do this separately if preferred. Also, do you think we should get Chudo's feedback?
> > 
> > 
> > Locally it looks good, that's strange
> 
> Hmm.. yes for some reason broken in vercel. We can maybe just create a new ticket if you prefer. Thanks so much for the changes. Yes we can follow up on any @chudo76 to give feedback later.

But all tables work like that, you have to scroll to the right to see all the data

**Comment by karthikbtf** [comment]
> > > > Looks great thanks! For mobile the inputs use up table width. Unrelated to this PR for sure. Moving the Table out of the top level grid container should fix it.. small change but sure we can do this separately if preferred. Also, do you think we should get Chudo's feedback?
> > > 
> > > 
> > > Locally it looks good, that's strange
> > 
> > 
> > Hmm.. yes for some reason broken in vercel. We can maybe just create a new ticket if you prefer. Thanks so much for the changes. Yes we can follow up on any @chudo76 to give feedback later.
> 
> But all tables work like that, you have to scroll to the right to see all the data

Yes, that is correct. I was referring to the input elements like language selector etc.
We can make that section independent of the table width with Grids. We do that in some other places.

**Comment by karthikbtf** [comment]
> > > > > Looks great thanks! For mobile the inputs use up table width. Unrelated to this PR for sure. Moving the Table out of the top level grid container should fix it.. small change but sure we can do this separately if preferred. Also, do you think we should get Chudo's feedback?
> > > > 
> > > > 
> > > > Locally it looks good, that's strange
> > > 
> > > 
> > > Hmm.. yes for some reason broken in vercel. We can maybe just create a new ticket if you prefer. Thanks so much for the changes. Yes we can follow up on any @chudo76 to give feedback later.
> > 
> > 
> > But all tables work like that, you have to scroll to the right to see all the data
> 
> Yes, that is correct. I was referring to the input elements like language selector etc. We can make that section independent of the table width with Grids. We do that in some other places.

The problem is unrelated to this PR :) I will create a ticket for us later.

**Comment by chudo76** [comment]
Looks a bit odd with a three-column row on top of a four-column row but I don't have a good alternative so I think we're good for now. The form fields look much better at full-width, though. Thanks!

**Pull request merged**
