### PR TITLE
SW-3236 Add Subzones and Monitoring Plots

### PR DESCRIPTION
**Pull request by charlie-tf**
Make necessary changes to FE code to accomodate the renaming of plots to
planting subzones and the addition of monitoring plots inside of those.
We update the types from the OpenAPI spec, but the bulk of the changes
here are renames. I've gone through the withdrawal and reassignment flows,
as well as verifying that the maps are working correctly.

Note, this won't work correctly without the BE changes in https://github.com/terraware/terraware-server/pull/1028

### CODE REVIEW

**Review by karthikbtf — APPROVED** [review]
lgtm 👍 and thanks for this sweeping effort 🙏 
like you mentioned, was unable to test but looks good..

**Comment by karthikbtf** [comment]
The subzone selector label in plants dashboard chart may need a style lift.. i think the label has a min-width that needs to be increased.

Terraware App 2023-03-19 07-45-27

Terraware App 2023-03-19 07-45-06

Terraware App 2023-03-19 07-44-45

**Comment by charlie-tf** [comment]
>The subzone selector label in plants dashboard chart may need a style lift.. i think the label has a min-width that needs to be increased.

I'll take a look at this. Thanks!

**Comment by karthikbtf** [comment]
> image
> 
> image

👍🙏🏻

**Pull request merged**
