### PR TITLE
SW-4520 Create reports settings pre-setup page, show in reports v2 view when the reports settings have not been configured

### PR DESCRIPTION
**Pull request by nickgraz**

### CODE REVIEW

**Comment by nickgraz** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2004?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #2002** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2002?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #2003** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2003?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #2004** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2004?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-web/2004?utm_source=stack-comment).

**Review by karthikbtf — APPROVED** [review]
screenshot?
is there a plan for organization vs project level report settings editing? just curious.

**Comment by nickgraz** [comment]
Yea that will be coming in a later PR. [Here's](https://terraformation.atlassian.net/browse/SW-4520) the ticket

**Comment by nickgraz** [comment]
### Merge activity

* **Jan 5, 3:26 PM**: @nickgraz started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-web/2004).

**Pull request merged**
