### PR TITLE
Strip Accelerator file prefix in AcceleratorRouter/Accelerator* components

### PR DESCRIPTION
**Pull request by karthikbtf**
- as it seems redundant

### CODE REVIEW

**Comment by karthikbtf** [comment]
@nickgraz if we prefer to skip the rename for IDE purposes that's fine too. Maybe a naming convention to be addressed across the board.

**Review by nickgraz — APPROVED** [review]
🙏

**Comment by joshbuchea** [comment]
This may not be exactly what you were referring to when you mentioned naming conventions @karthikbtf, but I'm not a fan of having a bunch of `index` files across a codebase. In my primary editor VS Code, multiple index files are distinguished by including the folder in the tab name (`folder1/index`, `folder2/index`, etc.) but this results in very wide file tabs and limits the amount of open files I can visibly see in my editor at once.

Not a big deal ultimately, but perhaps it's worth discussing at SW Engineering Team Roundtable?

**Comment by karthikbtf** [comment]
> This may not be exactly what you were referring to when you mentioned naming conventions @karthikbtf, but I'm not a fan of having a bunch of `index` files across a codebase. In my primary editor VS Code, multiple index files are distinguished by including the folder in the tab name (`folder1/index`, `folder2/index`, etc.) but this results in very wide file tabs and limits the amount of open files I can visibly see in my editor at once.
> 
> Not a big deal ultimately, but perhaps it's worth discussing at SW Engineering Team Roundtable?

@joshbuchea sure, if it's something you'd like to discuss, it's worth discussing. There are pros & cons to having index files.

**Pull request merged**
