### PR TITLE
SW-2123: Responsive Page Layouts -> Onboarding

### PR DESCRIPTION
**Pull request by joshbuchea**
This PR updates the no organization landing page to align with the new [visual updates](https://www.figma.com/file/aLIG1C6uIMyBWiTopSluxe/Visual-Refresh?node-id=853%3A108782&t=TqgSlECxJ34AklsU-0).

## Screenshots

Desktop:

Screen Shot 2022-11-21 at 2 22 11 PM

Tablet:

localhost_3000_welcome(iPad Mini)

Mobile:

localhost_3000_welcome(iPhone SE)

### CODE REVIEW

**Comment by joshbuchea** [comment]
@hannah-cai heads up that I left a few questions in Figma re: to these changes. One quick question I had was — have the colors been updated in zeroheight for blobby icons, or does that still need to happen?

**Review by karthikbtf — APPROVED** [review]
Looks good 👍

**Comment by hannah-cai** [comment]
hard to tell through the screenshots but everything looks good as long as the tokens have been updated! the text looks like it's pure black, it should be tw-clr-txt

**Comment by joshbuchea** [comment]
@hannah-cai is the text color `tw-clr-txt` applied in all pages of the new visual updates designs? Or just this page?

**Comment by joshbuchea** [comment]
Will merge this PR once [this related PR in web-components](https://github.com/terraware/web-components/pull/159) is merged.

**Comment by joshbuchea** [comment]
@hannah-cai ok thanks for clarifying. This PR is focused on changes to this page, global font styles will be adjusted in another related PR.

**Comment by joshbuchea** [comment]
Ah oops, I forgot to push up some local changes 😅 Opening a follow-up PR soon!

**Pull request merged**
