### PR TITLE
SW-5206: Update module routes

### PR DESCRIPTION
**Pull request by joshbuchea**
This PR includes updates to the module route keys & paths.

Note: Plural naming was used to follow existing route conventions.

### CODE REVIEW

**Review by nickgraz — APPROVED** [review]
Looks good!

**Comment by joshbuchea** [comment]
@nickgraz so it turns out these path changes break the module pages, I believe because the route is now being picked up and handled by the `ProjectsRouter` rather than the `ModulesRouter`. Is it ok to move the three project module related routes into the `ProjectsRouter` or is there an alternative approach we're prefer?

**Comment by joshbuchea** [comment]
Ah but then we need to move the views as well 🤔

I think we may be able to just move the `ModulesRouter` above the `ProjectsRouter` and it would be picked up, but then we rely on route order within the `OrgRouter`. Perhaps that's ok?

**Comment by joshbuchea** [comment]
Went ahead and made the latter change since it's the simplest.

**Pull request merged**
