### PR TITLE
SW-4540 Planting site create stepper flow with placeholder content

### PR DESCRIPTION
**Pull request by karthikbtf**
- created a form with mui stepper integration
- placeholder content for now
- created wrapper component that distinguishes between simple and detailed sites, to set the relevant steps for the stepper
- this is no super mobile friendly yet, will ask @chudo76  to take a look, any changes to mobile will be followed up separately

Attaching videos:

screencast 2023-12-20 14-38-48

screencast 2023-12-20 14-40-15

screencast 2023-12-20 14-43-55

### CODE REVIEW

**Comment by karthikbtf** [comment]
@nickgraz when you get a chance

**Comment by karthikbtf** [comment]
> @nickgraz when you get a chance

I have one small change coming up, will update this PR.

**Review by nickgraz — APPROVED** [review]
Looks good to me, sorry for the delay

**Comment by karthikbtf** [comment]
> Looks good to me, sorry for the delay

Thanks Nick, I had one update in-flight as you were reviewing. Stubbed out entry points for the various steps.

**Comment by karthikbtf** [comment]
> > Looks good to me, sorry for the delay
> 
> Thanks Nick, I had one update in-flight as you were reviewing. Stubbed out entry points for the various steps.

When you get a chance can you look at the updates?

**Comment by chudo76** [comment]
> * this is no super mobile friendly yet, will ask @chudo76  to take a look, any changes to mobile will be followed up separately

They have a [mobile stepper](https://mui.com/material-ui/react-stepper/#mobile-stepper) but I'm not convinced drawing a detailed planting site is something that should be done on a small touch screen.

**Comment by karthikbtf** [comment]
> > * this is no super mobile friendly yet, will ask @chudo76  to take a look, any changes to mobile will be followed up separately
> 
> They have a [mobile stepper](https://mui.com/material-ui/react-stepper/#mobile-stepper) but I'm not convinced drawing a detailed planting site is something that should be done on a small touch screen.

Mobile usage is an expectation in the PRD, not sure if users will use it that way. 
I'd say the current stepper is still mobile usable. The mobile stepper is a completely different layout.

**Comment by karthikbtf** [comment]
Getting this in for now, this is an intermediate state and will make review related changes as we go along.

**Comment by chudo76** [comment]
> Mobile usage is an expectation in the PRD, not sure if users will use it that way. I'd say the current stepper is still mobile usable. The mobile stepper is a completely different layout.

@karthikbtf Confirmed with Alex that we don't expect people to be able to go through this flow on mobile. We can leave as is, and/or we can add a page message that tells the user to go through this flow on desktop that is `display: none;` by default but appears on smaller, mobile breakpoints.

**Comment by karthikbtf** [comment]
> > Mobile usage is an expectation in the PRD, not sure if users will use it that way. I'd say the current stepper is still mobile usable. The mobile stepper is a completely different layout.
> 
> @karthikbtf Confirmed with Alex that we don't expect people to be able to go through this flow on mobile. We can leave as is, and/or we can add a page message that tells the user to go through this flow on desktop that is `display: none;` by default but appears on smaller, mobile breakpoints.

Captured here https://terraformation.atlassian.net/browse/SW-4691

**Pull request merged**
