### PR TITLE
Updated translations from Phrase

### PR DESCRIPTION
**Pull request by terraware-phrase**
Exported the most recent locale files from Phrase

### CODE REVIEW

**Review by karthikbtf — APPROVED** [review]

**Comment by charlie-tf** [comment]
I wonder if this is the wrong sense of the word, "outstanding"
image

vs
image

@constanzauanini, your thoughts?

**Comment by karthikbtf** [comment]
> I wonder if this is the wrong sense of the word, "outstanding" image
> 
> vs image
> 
> @constanzauanini, your thoughts?

Good one. Bring this up in the translations slack channel maybe. Perhaps calls this Pending

**Comment by constanzauanini** [comment]
> > I wonder if this is the wrong sense of the word, "outstanding" image
> > vs image
> > @constanzauanini, your thoughts?
> 
> Good one. Bring this up in the translations slack channel maybe. Perhaps calls this Pending

Yes, this seems wrong. If we want to mean "pending" it is definitely not "destacado", I would use "pendiente". I don't know where are we using this word

**Comment by charlie-tf** [comment]
> > > I wonder if this is the wrong sense of the word, "outstanding" 
> > > ...
> > > @constanzauanini, your thoughts?
> > 
> > Good one. Bring this up in the translations slack channel maybe. Perhaps calls this Pending
> 
> Yes, this seems wrong. If we want to mean "pending" it is definitely not "destacado", I would use "pendiente". I don't know where are we using this word

@constanzauanini Oh, I'm sorry for not including the context of where it is used. This is used in the observations table to indicate that an observation is scheduled but not yet started. Thanks for your input

**Comment by karthikbtf** [comment]
@charlie-tf @constanzauanini maybe we could rename the key to OBSERVATION_STATUS_OUTSTANDING to disambiguate (this is a corner case, not sure we need to list other statuses with OBSERVATION_STATUS_ prefix).

**Comment by karthikbtf** [comment]
> @charlie-tf @constanzauanini maybe we could rename the key to OBSERVATION_STATUS_OUTSTANDING to disambiguate (this is a corner case, not sure we need to list other statuses with OBSERVATION_STATUS_ prefix).

any thoughts?

**Comment by karthikbtf** [comment]
> > > @charlie-tf @constanzauanini maybe we could rename the key to OBSERVATION_STATUS_OUTSTANDING to disambiguate (this is a corner case, not sure we need to list other statuses with OBSERVATION_STATUS_ prefix).
> > 
> > 
> > any thoughts?
> 
> Let's do that. The renamed string will most likely get the translation kicked off.

Ok, will do.

**Pull request closed without merging**
