### PR TITLE
SW-1992 (WIP) upgrade node version for github actions

### PR DESCRIPTION
**Pull request by karthikbtf**
- this is a test
- See https://github.com/actions/setup-node
- See https://github.com/actions/checkout

### CODE REVIEW

**Review by constanzauanini — APPROVED** [review]
Are we updating just to be updated or any other reason?

**Comment by karthikbtf** [comment]
> Are we updating just to be updated or any other reason?

Node version 12 is deprecated and no longer supported from early 2023. They are giving us time to upgrade to 16.
This PR is still WIP, current changes are not working.. need to investigate some more.

**Comment by constanzauanini** [comment]
> > Are we updating just to be updated or any other reason?
> 
> Node version 12 is deprecated and no longer supported from early 2023. They are giving us time to upgrade to 16. This PR is still WIP, current changes are not working.. need to investigate some more.

Oh, ok! But we are not specifically setting node version to be 12, are we?

**Comment by karthikbtf** [comment]
> > > Are we updating just to be updated or any other reason?
> > 
> > 
> > Node version 12 is deprecated and no longer supported from early 2023. They are giving us time to upgrade to 16. This PR is still WIP, current changes are not working.. need to investigate some more.
> 
> Oh, ok! But we are not specifically setting node version to be 12, are we?

Correct, it's in the existing github actions we use, they set node to 12. version 3 for some of them use 16.
Some of the other github actions don't have new versions, I am still figuring this out.

**Comment by karthikbtf** [comment]
this was done

**Pull request closed without merging**
