### PR TITLE
SW-4761 Create AccessionsRouter and move all accessions views and sub components to scenes directory

### PR DESCRIPTION
**Pull request by nickgraz**
SW-4761 Create AccessionsRouter and move all accessions views and sub components to scenes directory

Delete src/components/accession2 dir

### CODE REVIEW

**Comment by nickgraz** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2067?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #2050** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2050?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #2061** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2061?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #2062** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2062?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #2063** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2063?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #2064** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2064?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #2065** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2065?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
              * **PR #2066** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2066?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                * **PR #2067** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2067?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
                  * **PR #2068** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2068?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-web/2067?utm_source=stack-comment).

**Review by karthikbtf — APPROVED** [review]
move the other `checkin` scene under this directory as well, since it is an accessions flow

**Comment by nickgraz** [comment]
The problem with that view is that it isn't technically within this router since the URL is /checkin not /accessions/checkin. But you are right, it is technically within the "accessions" stuff, but it somewhat deviates from the hierarchy. I don't mind moving it, but want you to confirm, given that info.

**Comment by karthikbtf** [comment]
> The problem with that view is that it isn't technically within this router since the URL is /checkin not /accessions/checkin. But you are right, it is technically within the "accessions" stuff, but it somewhat deviates from the hierarchy. I don't mind moving it, but want you to confirm, given that info.

Got it, not too sure on the history of this route. It isn't used in any notifications, should be safe to rename the route.
But.. maybe best to keep things as they are and revisit later.

**Comment by nickgraz** [comment]
OK I will leave it for now and ask around, I agree it would be best to rename it

**Comment by sgrimm** [comment]
### Merge activity

* **Jan 25, 3:38 PM**: @sgrimm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-web/2067).

**Pull request merged**
