### PR TITLE
SW-3440 Fix change status/quantities modal in seedlings batches when the numbers are large

### PR DESCRIPTION
**Pull request by karthikbtf**
- code was using the localized display value (with commas) for math instead of the raw values..
- switched to raw
- also fixed some UX issues like error validation and spinner

### CODE REVIEW

**Comment by karthikbtf** [comment]
@chudo76 give this a try, also showing a spinner on save now.. and if you save without an entry we flag that now.

**Review by charlie-tf — APPROVED** [review]
Mostly makes sense. Just curious why the modal was made to unmount/remount instead of controlling the open prop

**Comment by karthikbtf** [comment]
> Mostly makes sense. Just curious why the modal was made to unmount/remount instead of controlling the open prop

Thanks @charlie-tf  - in case it helps, the "xyz(raw)" properties are the actual numbers (as provided by terraware-server search). The "xyz" properties are localized for display only. We had switched to using the '(raw)' properties sometime back but missed this modal. We cannot do "30,000 - 5" in javascript, it yields 'NaN'. The 'raw' value is '30000' without the comma.

Re: the open boolean property, there are two reasons for why I did it this way:

1) Here specifically, we have one of them per row in the table. The cost of having one mounted but invisible per row is more expensive that mounting/unmounting one at a time upon menu click.

2) I have been switching to this approach every where we have modals - the cost of unmount/remount is less than ensuring a cleaned up modal - which often they aren't.. just buggy. It it was one modal that's fine.. we have a lot of modals with a lot of content.. and often with too much context (when the modals should be separated by context). A lot of bugs have been uncovered, I wonder if the boolean open pattern is best for static content.

**Comment by charlie-tf** [comment]
> > Mostly makes sense. Just curious why the modal was made to unmount/remount instead of controlling the open prop
> 
> Thanks @charlie-tf - in case it helps, the "xyz(raw)" properties are the actual numbers (as provided by terraware-server search). The "xyz" properties are localized for display only. We had switched to using the '(raw)' properties sometime back but missed this modal. We cannot do "30,000 - 5" in javascript, it yields 'NaN'. The 'raw' value is '30000' without the comma.
> 
> Re: the open boolean property, there are two reasons for why I did it this way:
> 
> 1. Here specifically, we have one of them per row in the table. The cost of having one mounted but invisible per row is more expensive that mounting/unmounting one at a time upon menu click.
> 2. I have been switching to this approach every where we have modals - the cost of unmount/remount is less than ensuring a cleaned up modal - which often they aren't.. just buggy. It it was one modal that's fine.. we have a lot of modals with a lot of content.. and often with too much context (when the modals should be separated by context). A lot of bugs have been uncovered, I wonder if the boolean open pattern is best for static content.

Great reasons! Thanks for taking the time to explain it to me :)

**Comment by karthikbtf** [comment]
> > > Mostly makes sense. Just curious why the modal was made to unmount/remount instead of controlling the open prop
> > 
> > 
> > Thanks @charlie-tf - in case it helps, the "xyz(raw)" properties are the actual numbers (as provided by terraware-server search). The "xyz" properties are localized for display only. We had switched to using the '(raw)' properties sometime back but missed this modal. We cannot do "30,000 - 5" in javascript, it yields 'NaN'. The 'raw' value is '30000' without the comma.
> > Re: the open boolean property, there are two reasons for why I did it this way:
> > 
> > 1. Here specifically, we have one of them per row in the table. The cost of having one mounted but invisible per row is more expensive that mounting/unmounting one at a time upon menu click.
> > 2. I have been switching to this approach every where we have modals - the cost of unmount/remount is less than ensuring a cleaned up modal - which often they aren't.. just buggy. It it was one modal that's fine.. we have a lot of modals with a lot of content.. and often with too much context (when the modals should be separated by context). A lot of bugs have been uncovered, I wonder if the boolean open pattern is best for static content.
> 
> Great reasons! Thanks for taking the time to explain it to me :)

Thanks :) it was a good call-out we may still need to address. Once Constanza is back we can bring this up in a discussion. For consistency we need to pick one over the other, evaluate costs..etc. maybe start a styleguide/best-practices-doc at some point.

**Pull request merged**
