### PR TITLE
SW-5825: Can't type accents in Questionnaire Deliverable inputs

### PR DESCRIPTION
**Pull request by joshbuchea**
This PR includes changes to how state is managed for text values in Questionnaire Deliverables. These changes resolve two issues:

- SW-5825: Can't type accents in Questionnaire Deliverable inputs
- SW-5853: Typing mid-word will automatically moved the cursor to the end of the text after one letter is typed

### CODE REVIEW

**Review by constanzauanini — APPROVED** [review]
Working correctly in Vercel!

**Comment by nickgraz** [comment]
The inputs don't load for me in Vercel
SCR-20240822-jecq

**Comment by nickgraz** [comment]
I'm able to see the bug pretty easily, but I don't really understand the changes. Can you give a one liner about what was happening and how this fixes it? Also, do these changes need to be done in the other `VariableDetailsInput` component?

**Comment by joshbuchea** [comment]
@graz I'm not sure why the inputs aren't rendering for you on Vercel, they're rendering locally and on Vercel for me

**Comment by joshbuchea** [comment]
Sure, removing the extra state (`textValuesList`) and using `values` directly to render the inputs resolved the cursor reset issues caused by `useEffect`.

**Comment by joshbuchea** [comment]
`VariableDetailsInput` should probably be updated also since it shares much of the same code, I created a ticket to address that here: https://terraformation.atlassian.net/browse/SW-5888

**Pull request merged**
