### PR TITLE
Display monitoring plot observation photos

### PR DESCRIPTION
**Pull request by karthikbtf**
- mostly a copy of what we do in nursery withdrawals details plus some customization for monitoring plots
- added photos in staging, switch to dev org and go here /observations/56/3/106/270028

Terraware App 2023-06-13 11-38-26

Terraware App 2023-06-13 11-33-30

Terraware App 2023-06-13 11-49-04

### CODE REVIEW

**Comment by karthikbtf** [comment]
To test: https://tree-location-web-git-karthik-photos-terraformation.vercel.app/observations/56/3/106/270028

**Review by charlie-tf — APPROVED** [review]
Looks good!

**Comment by karthikbtf** [comment]
> Looks good!

Thanks @charlie-tf . Wanted to run this by you.. the only differences between here and nursery withdrawals photos are height/width of thumbnails and object/cover image css. Nursery withdrawals photos uses varied widths for thumbnails and shows the entire image. Would it be worth extracting this out and reusing for nursery withdrawals as well (will change some of the current behavior). Potentially reuse for accessions as well.

**Comment by karthikbtf** [comment]
> > > Looks good!
> > 
> > 
> > Thanks @charlie-tf . Wanted to run this by you.. the only differences between here and nursery withdrawals photos are height/width of thumbnails and object/cover image css. Nursery withdrawals photos uses varied widths for thumbnails and shows the entire image. Would it be worth extracting this out and reusing for nursery withdrawals as well (will change some of the current behavior). Potentially reuse for accessions as well.
> 
> That seems like a worthwhile thing to extract into its own component. A followup / improvement ticket is fine

I can extract it out as part of this PR. Is that a 'yes' to replacing the nursery withdrawals photos? I can do the replacements as a follow up PR.

**Comment by charlie-tf** [comment]
> 

Followup for replacements sounds fine to me

**Comment by karthikbtf** [comment]
> > 
> 
> Followup for replacements sounds fine to me

Cool, created [this](https://terraformation.atlassian.net/browse/SW-3758). Refactored this PR.

**Review by charlie-tf — APPROVED** [review]
Nice!

**Pull request merged**
