### PR TITLE
SW-2208 handle inventory when species no longer exists

### PR DESCRIPTION
**Pull request by karthikbtf**
- check for species id in renderer
- we can no longer show species info or details by species with a link
- awaiting PM response on this fix

Terraware App 2022-11-09 14-52-08

### CODE REVIEW

**Comment by constanzauanini** [comment]
I think Alison wants to still be able to see the species name if it's deleted

**Comment by karthikbtf** [comment]
> I think Alison wants to still be able to see the species name if it's deleted

yes, not sure it is feasible, will check with Steve. In any case, we need this fix -without this inventory page won't load if there is a deleted species in inventory. will show error page. will follow up on jira.

**Comment by constanzauanini** [comment]
> > I think Alison wants to still be able to see the species name if it's deleted
> 
> yes, not sure it is feasible, will check with Steve. In any case, we need this fix -without this inventory page won't load if there is a deleted species in inventory. will show error page. will follow up on jira.

Ok, let's merge this fix and we can follow up later

**Comment by karthikbtf** [comment]
> > > I think Alison wants to still be able to see the species name if it's deleted
> > 
> > 
> > yes, not sure it is feasible, will check with Steve. In any case, we need this fix -without this inventory page won't load if there is a deleted species in inventory. will show error page. will follow up on jira.
> 
> Ok, let's merge this fix and we can follow up later

Thanks, yes, Allison recommended the same. The fixes are a larger enhancement discussion for later.
See JIRA when you get a chance, there will be small changes in species results.

**Pull request merged**
