### PR TITLE
SW-2444 Improvements to outplant withdraw flow

### PR DESCRIPTION
**Pull request by karthikbtf**
- show selected species (filtered by from: nursery)
- show total ready quantity for single batch outplant purpose
- see figma https://www.figma.com/file/yRSfer1xtWKAJr4IETPml1/Tracking-by-Sampling?node-id=2325%3A530101&t=K6QLnMAreJXQYNKa-4

Terraware App 2022-12-19 08-22-55

Terraware App 2022-12-19 08-22-37

Terraware App 2022-12-19 08-22-14

Terraware App 2022-12-19 08-21-56

### CODE REVIEW

**Review by joshbuchea — APPROVED** [review]
👌

**Review by constanzauanini — APPROVED** [review]
For me, in mobile view it looks like "Total ready quantity" is missing some padding or margin in the top

**Comment by karthikbtf** [comment]
> For me, in mobile view it looks like "Total ready quantity" is missing some padding or margin in the top

@constanzauanini this should be fixed now. Not sure what the recommended margin between components should be - we may need to clean this up further separately as some elements seem to have more margin than others at some breakpoints.

**Comment by constanzauanini** [comment]
> > For me, in mobile view it looks like "Total ready quantity" is missing some padding or margin in the top
> 
> @constanzauanini this should be fixed now. Not sure what the recommended margin between components should be - we may need to clean this up further separately as some elements seem to have more margin than others at some breakpoints.

This looks much better now. Thank you!

**Review by constanzauanini — APPROVED** [review]

**Pull request merged**
