### PR TITLE
Update monitoring chart time zone picker location

### PR DESCRIPTION
**Pull request by karthikbtf**
- moved it to the right most card

Terraware App 2023-01-12 16-09-15

### CODE REVIEW

**Review by constanzauanini — APPROVED** [review]
Thanks! I forgot to do it yesterday

**Comment by karthikbtf** [comment]
> Thanks! I forgot to do it yesterday


Thanks @constanzauanini  - btw, I tried updating the time zone but the x-axis range stayed the same. Can you take a look - it's possible I didn't test it right since I have no data.

**Comment by karthikbtf** [comment]
> > > Thanks! I forgot to do it yesterday
> > 
> > 
> > Thanks @constanzauanini - btw, I tried updating the time zone but the x-axis range stayed the same. Can you take a look - it's possible I didn't test it right since I have no data.
> 
> Working for me! montiro [ montiro ](https://user-images.githubusercontent.com/5919083/212346793-6ded2b09-1b3f-4f35-8679-8da5eb11fa2d.gif) [ ](https://user-images.githubusercontent.com/5919083/212346793-6ded2b09-1b3f-4f35-8679-8da5eb11fa2d.gif)

I meant the range min and max on the x-axis. It is not changing, even in your video. This is not coming from the data points, i think it's an option in the chart... we may need to just apply the time zone there. The first and last labels on the x-axis.

**Comment by constanzauanini** [comment]
> > > Thanks! I forgot to do it yesterday
> > 
> > 
> > Thanks @constanzauanini - btw, I tried updating the time zone but the x-axis range stayed the same. Can you take a look - it's possible I didn't test it right since I have no data.
> 
> Working for me! montiro [ montiro ](https://user-images.githubusercontent.com/5919083/212346793-6ded2b09-1b3f-4f35-8679-8da5eb11fa2d.gif) [ ](https://user-images.githubusercontent.com/5919083/212346793-6ded2b09-1b3f-4f35-8679-8da5eb11fa2d.gif)

I just discovered the bug.  I didn't add timezone to the end date! Will make the fix

**Pull request merged**
