### PR TITLE
SW-2469 Add spinner when withdraw is happening

### PR DESCRIPTION
**Pull request by karthikbtf**
- see video

@chudo76 thoughts on this spinner?

screencast 2022-12-06 12-10-58

### CODE REVIEW

**Review by constanzauanini — APPROVED** [review]

**Comment by chudo76** [comment]
> @chudo76 thoughts on this spinner?

Did we ever implement a ["processing" state](https://zeroheight.com/55ab6cc27/p/28e634-button/b/32e1a2/t/42aaa8) to our buttons? 

I think this is fine for now but rather than adding the "scrim" just to the main content area (where header and side navigation are not "scrimmed"), we probably want to do the whole viewport, like we do for _modal_ dialog boxes.

**Comment by karthikbtf** [comment]
> > @chudo76 thoughts on this spinner?
> 
> Did we ever implement a ["processing" state](https://zeroheight.com/55ab6cc27/p/28e634-button/b/32e1a2/t/42aaa8) to our buttons?
> 
> I think this is fine for now but rather than adding the "scrim" just to the main content area (where header and side navigation are not "scrimmed"), we probably want to do the whole viewport, like we do for _modal_ dialog boxes.

@chudo76 nice to see that we have a 'processing state'.. sadly no.. we do NOT have this anywhere in our web-app.
Happy to introduce that here as a starting point. 
Can you add that spinner asset to zeroheight?

**Comment by karthikbtf** [comment]
> > > @chudo76 thoughts on this spinner?
> > 
> > 
> > Did we ever implement a ["processing" state](https://zeroheight.com/55ab6cc27/p/28e634-button/b/32e1a2/t/42aaa8) to our buttons?
> > I think this is fine for now but rather than adding the "scrim" just to the main content area (where header and side navigation are not "scrimmed"), we probably want to do the whole viewport, like we do for _modal_ dialog boxes.
> 
> @chudo76 nice to see that we have a 'processing state'.. sadly no.. we do NOT have this anywhere in our web-app. Happy to introduce that here as a starting point. Can you add that spinner asset to zeroheight?

Updated to have full width/height skrim, was a zindex issue.
will get this in for now.. we may need to visit processing states across the UI and maybe track that as a separate scope.
will create a jira

**Comment by karthikbtf** [comment]
> > @chudo76 nice to see that we have a 'processing state'.. sadly no.. we do NOT have this anywhere in our web-app. Happy to introduce that here as a starting point. Can you add that spinner asset to zeroheight?
> 
> @karthikbtf Pretty sure we can do CSS animation to make this icon spin. (The spinner will need to match the design token color for the icons within buttons.)
> 
> Spinner asset: https://terraformation.zeroheight.com/styleguide/s/62196/p/34b2ef-iconography/b/51d761/i/48830783
> 
> Something icon like...?
> 
> ```
> svg.someclass {
>   animation: spinner 1.2s linear infinite;
> } 
> 
> @keyframes spinner {
>   0% {
>     transform: rotate(0deg);
>   }
>   100% {
>     transform: rotate(360deg);
>   }
> }```
> ```

Awesome, thanks @chudo76 
I created this jira https://terraformation.atlassian.net/browse/SW-2472 for now
Will add this snippet + asset link in that jira.

**Pull request merged**
