### PR TITLE
rename ServerOrganization type to just Organization

### PR DESCRIPTION
**Pull request by karthikbtf**
- **no** other changes but this touches many files

### CODE REVIEW

**Comment by karthikbtf** [comment]
Why the rename? Not sure why we had 'Server' in the name - we don't use this pattern in other types.

**Review by charlie-tf — APPROVED** [review]
Thanks!

**Comment by constanzauanini** [comment]
> Why the rename? Not sure why we had 'Server' in the name - we don't use this pattern in other types.

I think it was because we had another Organization type in the FE, but it may not exist anymore

**Review by constanzauanini — APPROVED** [review]

**Comment by karthikbtf** [comment]
> > Why the rename? Not sure why we had 'Server' in the name - we don't use this pattern in other types.
> 
> I think it was because we had another Organization type in the FE, but it may not exist anymore

Thanks @constanzauanini - yes I noticed we don't have another one. This rename seems consistent with other types we have.. and just seems simpler/cleaner. hope that's ok.

**Pull request merged**
