### PR TITLE
SW-5150 Use Dropdown Option as selected option

### PR DESCRIPTION
**Pull request by tommylau523**

### CODE REVIEW

**Comment by tommylau523** [comment]
* **#2464** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2464?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @tommylau523 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by karthikbtf — APPROVED** [review]
👍

**Comment by tommylau523** [comment]
Hi @karthikbtf, I updated the logic on how the correct option is found. Will be worthwhile for another look.

**Comment by tommylau523** [comment]
### Merge activity

* **Apr 3, 9:04 PM EDT**: @tommylau523 merged this pull request with [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-web/2464).

**Pull request merged**
