### PR TITLE
SW-4518 Add project name column to 'select batch quantites for withdrawal' table

### PR DESCRIPTION
**Pull request by nickgraz**

### CODE REVIEW

**Comment by nickgraz** [comment]
Ah, yes

**Comment by nickgraz** [comment]
Good catch, that is fixed now

**Review by karthikbtf — APPROVED** [review]

**Comment by karthikbtf** [comment]
> Good catch, that is fixed now
> 
>  [  ](https://camo.githubusercontent.com/6a75792fac47a79aec18680187b333125300cc95d1265ef8c3621ffc0420f618/68747470733a2f2f67726170686974652d757365722d75706c6f616465642d6173736574732d70726f642e73332e616d617a6f6e6177732e636f6d2f774a6e505839774c5a416b6947584542464a784c2f38313964333435332d363765342d343162652d383332382d6439393430356536306333662e676966) [ ](https://camo.githubusercontent.com/6a75792fac47a79aec18680187b333125300cc95d1265ef8c3621ffc0420f618/68747470733a2f2f67726170686974652d757365722d75706c6f616465642d6173736574732d70726f642e73332e616d617a6f6e6177732e636f6d2f774a6e505839774c5a416b6947584542464a784c2f38313964333435332d363765342d343162652d383332382d6439393430356536306333662e676966)

🚀

**Comment by nickgraz** [comment]
### Merge activity

* **Jan 3, 3:21 PM**: @nickgraz started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-web/1980).

**Pull request merged**
