### PR TITLE
Remove the page header ref passed down into the TableWithSearchFilters, the functionality is already handled view the PageHeaderWrapper

### PR DESCRIPTION
**Pull request by nickgraz**

### CODE REVIEW

**Comment by nickgraz** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2315?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2315** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2315?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2312** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2312?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2311** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2311?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nickgraz and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by nickgraz** [comment]
@karthikbtf you were right, it is already handled.

**Review by karthikbtf — APPROVED** [review]
🙌

**Comment by nickgraz** [comment]
### Merge activity

* **Mar 14, 11:07 AM EDT**: @nickgraz started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-web/2315).

**Pull request merged**
