### PR TITLE
SW-2817 TrackingService refactor 

### PR DESCRIPTION
**Pull request by karthikbtf**
- moved api into a tracking service
- fixed planting sites table to sort based on BE data

### CODE REVIEW

**Comment by constanzauanini** [comment]
Timezone should be order in the frontend? It's not working now

**Comment by karthikbtf** [comment]
> Timezone should be sort in the frontend? It's not working now

Not sure I understand.. this has nothing to do with time zones yes?

**Comment by karthikbtf** [comment]
> > Timezone should be sort in the frontend? It's not working now
> 
> Not sure I understand.. this has nothing to do with time zones yes?

oh the planting sites table.. ok i will make that presorted=false if it's time zone

**Comment by karthikbtf** [comment]
> > > Timezone should be sort in the frontend? It's not working now
> > 
> > 
> > Not sure I understand.. this has nothing to do with time zones yes?
> 
> oh the planting sites table.. ok i will make that presorted=false if it's time zone

fixed .. try it in vercel after it builds

**Comment by constanzauanini** [comment]
> > > Timezone should be sort in the frontend? It's not working now
> > 
> > 
> > Not sure I understand.. this has nothing to do with time zones yes?
> 
> oh the planting sites table.. ok i will make that presorted=false if it's time zone

Yes, sorry I didn't explain well !

**Comment by karthikbtf** [comment]
> > > > Timezone should be sort in the frontend? It's not working now
> > > 
> > > 
> > > Not sure I understand.. this has nothing to do with time zones yes?
> > 
> > 
> > oh the planting sites table.. ok i will make that presorted=false if it's time zone
> 
> Yes, sorry I didn't explain well !

Good call, thanks for catching this.. I tested the names and numbers only.

**Review by constanzauanini — APPROVED** [review]

**Comment by karthikbtf** [comment]
> Thanks! Working now, just noticied one timezone in the wrong order, but nothing to do with this changes: Screenshot 2023-02-14 at 12 03 44

that's strange.. why this order? is it happening in staging without the changes? curious where the bug is

**Comment by karthikbtf** [comment]
> > Thanks! Working now, just noticied one timezone in the wrong order, but nothing to do with this changes: Screenshot 2023-02-14 at 12 03 44
> 
> that's strange.. why this order? is it happening in staging without the changes? curious where the bug is

oh yea.. this is a bug in the table.. we should probably look into it

**Comment by karthikbtf** [comment]
> > > Thanks! Working now, just noticied one timezone in the wrong order, but nothing to do with this changes: Screenshot 2023-02-14 at 12 03 44
> > 
> > 
> > that's strange.. why this order? is it happening in staging without the changes? curious where the bug is
> 
> oh yea.. this is a bug in the table.. we should probably look into it

actually no, this could be a bug in how the sites rows are being populated. i will check it out

**Comment by constanzauanini** [comment]
> > Thanks! Working now, just noticied one timezone in the wrong order, but nothing to do with this changes: Screenshot 2023-02-14 at 12 03 44
> 
> that's strange.. why this order? is it happening in staging without the changes? curious where the bug is

I just tested timezones in seedbanks in staging and it's also not working properly

**Comment by karthikbtf** [comment]
> > > Thanks! Working now, just noticied one timezone in the wrong order, but nothing to do with this changes: Screenshot 2023-02-14 at 12 03 44
> > 
> > 
> > that's strange.. why this order? is it happening in staging without the changes? curious where the bug is
> 
> I just tested timezones in seedbanks in staging and it's also not working properly

This is because the rows contain the time zone ids, not the display names.. it is sorted by id but displayed as name. We have to fix all the tables that show time zones.. we can do that separately.

**Comment by karthikbtf** [comment]
> > > > Thanks! Working now, just noticied one timezone in the wrong order, but nothing to do with this changes: Screenshot 2023-02-14 at 12 03 44
> > > 
> > > 
> > > that's strange.. why this order? is it happening in staging without the changes? curious where the bug is
> > 
> > 
> > I just tested timezones in seedbanks in staging and it's also not working properly
> 
> This is because the rows contain the time zone ids, not the display names.. it is sorted by id but displayed as name. We have to fix all the tables that show time zones.. we can do that separately.

Fixed in a separate PR https://github.com/terraware/terraware-web/pull/1191

**Pull request merged**
