### PR TITLE
SW-3998 Get exact matches for selected planting site on withdrawals page

### PR DESCRIPTION
**Pull request by karthikbtf**
- BE returns planting sites whose names contain the selected planting site name, eg. if selected site is 'site', responses will also include 'site1' if they exist
- [see](https://terraformation.atlassian.net/browse/SW-3070) for more context
- added another layer of filtering out non-exact names within client code

### CODE REVIEW

**Review by constanzauanini — APPROVED** [review]
Looks good!

**Review by charlie-tf — APPROVED** [review]
Looks good. Tested on withdrawals history page and works as expected

**Comment by karthikbtf** [comment]
> Looks good. Tested on withdrawals history page and works as expected

Thanks @charlie-tf 
The client side double filter is only because 'Exact' doesn't return exact matches, but also 'contained' matches. PR description has a link to a Jira that triggered the exact/contains behavior.
For now this should be good, unless the BE can return exact matches some other way.
There is a `destinationFacilityId`field in the table view but not sure that is actively populated, searching on that would be ideal. Perhaps a separate debug effort.

**Comment by karthikbtf** [comment]
i have one more change to make related to nursery withdrawals details url generation in reassignment flow (since it was changed to `/withdrawals/details`).. coming up shortly

**Comment by karthikbtf** [comment]
> i have one more change to make related to nursery withdrawals details url generation in reassignment flow (since it was changed to `/withdrawals/details`).. coming up shortly

this change is in now

**Comment by karthikbtf** [comment]
Converting to draft since the selector approach may not be correct.

**Comment by constanzauanini** [comment]
I think we can close this one @karthikbtf

**Pull request closed without merging**
