### PR TITLE
SW-4691 Disallow detailed planting site creation in mobile view

### PR DESCRIPTION
**Pull request by karthikbtf**
- show message asking user to switch to desktop app

Terraware App 2024-02-07 14-28-51

### CODE REVIEW

**Comment by karthikbtf** [comment]
@chudo76 thoughts

**Review by chudo76 — COMMENTED** [review]
I think we need a way for them to go back.. Maybe something like:

image

> **Feature Unavailable** 
> 
> This feature is only available from the desktop application.
>
> [Back to Planting Sites]

**Comment by karthikbtf** [comment]
> I think we need a way for them to go back.. Maybe something like:
> 
> image
> 
> > **Feature Unavailable**
> > This feature is only available from the desktop application.
> > [Back to Planting Sites]

Updated with this feedback, thanks 🙏

**Review by nickgraz — APPROVED** [review]
Makes sense

**Pull request merged**
