### PR TITLE
SW-4402 Allow upcoming observations to be rescheduled 

### PR DESCRIPTION
**Pull request by karthikbtf**
- also change criteria for which observations in the table can be rescheduled (in-progress/overdue and no observed plots)
- added a hasObservedTemporaryPlots to capture whether any type of plot was observed (in tandem with hasObservedPermanentPlots)
- refactor layout of page message that shows upcoming observations for reschedule, the site names have permalinks now and had to be constructed programmatically (removed from the string representation)

Terraware App 2023-11-01 08-46-48

Terraware App 2023-11-01 09-12-29

### CODE REVIEW

**Comment by karthikbtf** [comment]
This is the last task before I can mark the epic for QA, if anyone has a chance to look..

**Review by constanzauanini — APPROVED** [review]
Lgtm!

**Comment by karthikbtf** [comment]
> Lgtm!

Thanks @constanzauanini !!

**Comment by chudo76** [comment]
@karthikbtf Looks like font-size is slightly smaller for the "Reschedule" link (should be 16px instead of 14px?) but otherwise LGTM!

**Comment by karthikbtf** [comment]
> @karthikbtf Looks like font-size is slightly smaller for the "Reschedule" link (should be 16px instead of 14px?) but otherwise LGTM!

I did notice that but could only find 14 when inspecting in figma. Wasn't sure. Will fix it, thanks for the feedback 👍

**Pull request merged**
