### PR TITLE
SW-5768 Add modal to change document status

### PR DESCRIPTION
**Pull request by constanzauanini**
Screenshot 2024-09-06 at 4 09 16 PM

### CODE REVIEW

**Review by joshbuchea — DISMISSED** [review]
The changes look clean, but the example image doesn't quite match the image or linked designs in the ticket. Also, it seems like the top field needs a label?

**Comment by constanzauanini** [comment]
> The changes look clean, but the example image doesn't quite match the image or linked designs in the ticket. Also, it seems like the top field needs a label?

Yes, the design didn't take the status into account, so these requested changes are described in the comments in the Jira ticket.

**Comment by joshbuchea** [comment]
Ok I thought I may have been missing some information, thanks for the context @constanzauanini.

**Comment by joshbuchea** [comment]
Changes look good, but it still seems like there should be a label for the Internal Comments field?

**Comment by constanzauanini** [comment]
> Changes look good, but it still seems like there should be a label for the Internal Comments field?

Ok, I will add it. I wasn't sure if we needed it

**Review by joshbuchea — APPROVED** [review]
Thanks for adding the label 🙌

**Pull request merged**
