### PR TITLE
SW-4053 Show planting site name and end date in observations table, remove subzones

### PR DESCRIPTION
**Pull request by karthikbtf**
- See [JIRA](https://terraformation.atlassian.net/browse/SW-3999)

Terraware App 2023-11-01 15-10-11

### CODE REVIEW

**Comment by karthikbtf** [comment]
@chudo76 let me know thoughts on column default locations - yes they can be shuffled around and we save the layout.

**Review by chudo76 — APPROVED** [review]
Having the planting site column is super helpful! End date is useful, too. Column positions look good. 🙏

**Comment by karthikbtf** [comment]
> Having the planting site column is super helpful! End date is useful, too. Column positions look good. 🙏

Awesome, thanks 👍

**Comment by karthikbtf** [comment]
Looking for one more +1

**Review by constanzauanini — APPROVED** [review]
Looks good! Why do we want to remove sub-zone column? Is it not helpful?

**Comment by karthikbtf** [comment]
> Looks good! Why do we want to remove sub-zone column? Is it not helpful?

We show monitoring plots for the zone on the next page (not by subzones), thought subzones is not super helpful and uses up space. We will add it back if users want it I suppose.
Thanks for the review 🙏

**Pull request merged**
