### PR TITLE
SW-1750 Remove Accession Editing from Contributor Role

### PR DESCRIPTION
**Pull request by charlie-tf**
- add a userCanEdit const that checks for contributor role
  - is false if the role is contributor
- make all of the editing points conditional on userCanEdit
- check both desktop and mobile views
- TODO (followup): changes for viability test add/update/delete
- note: license-report and generated-schema were updated from 
`yarn license-report` and `yarn generate-types`

### CODE REVIEW

**Comment by charlie-tf** [comment]
broke an integration test, apparently? converting to draft to investigate

**Comment by charlie-tf** [comment]
nope, it was just flaky

**Comment by constanzauanini** [comment]
> * userCanEdit

e2e tests are flaky. We have a task to review that and also when removing v1 of accessions we will have to delete most of them

**Review by constanzauanini — APPROVED** [review]
Thanks for doing this change @charlie-tf !

**Pull request merged**
