### PR TITLE
Add styles for details and show site notes

### PR DESCRIPTION
**Pull request by constanzauanini**
Screen Shot 2022-09-28 at 11 50 48

TODO: Use file icon instead of folder icon

### CODE REVIEW

**Review by karthikbtf — COMMENTED** [review]
Thanks, can we check the mobile view?

**Comment by constanzauanini** [comment]
> Thanks, can we check the mobile view?

Mobile looks fine. I have a separate task to show the edit pencil icon on the right place

**Comment by karthikbtf** [comment]
> > Thanks, can we check the mobile view?
> 
> Mobile looks fine. I have a separate task to show the edit pencil icon on the right place

lol, ok i created a similar ticket.. https://terraformation.atlassian.net/browse/SW-1814

**Review by karthikbtf — COMMENTED** [review]
looks good - lets wait for the file icon and web-components version bump before merging?

**Comment by constanzauanini** [comment]
> > > Thanks, can we check the mobile view?
> > 
> > 
> > Mobile looks fine. I have a separate task to show the edit pencil icon on the right place
> 
> lol, ok i created a similar ticket.. https://terraformation.atlassian.net/browse/SW-1814

Marked as duplicated

**Review by karthikbtf — APPROVED** [review]
🎉

**Pull request merged**
