### PR TITLE
SW-2319 Add plants count by species popup to map in plants dashboard

### PR DESCRIPTION
**Pull request by karthikbtf**
- updated renderer types
- removed old renderer (not part of requirements)

Terraware App 2022-11-29 10-07-15

Terraware App 2022-11-29 10-06-56

Terraware App 2022-11-29 10-13-04

Terraware App 2022-11-29 10-12-48

### CODE REVIEW

**Review by charlie-tf — APPROVED** [review]
Looks great. Really easy to follow the code

**Comment by charlie-tf** [comment]
oh, looking at your screenshots: is the `x` in the upper right of the context box required?

**Comment by karthikbtf** [comment]
> Looks great. Really easy to follow the code

Thanks @charlie-tf !

**Review by constanzauanini — APPROVED** [review]
👍

**Pull request merged**
