### PR TITLE
SW-5704 Make live session instructions localizable

### PR DESCRIPTION
**Pull request by sgrimm**
Move the English text from the session instructions into the string
table.

This includes a few minor copy changes per the designs from SW-5704:

- The button label in the instructions matches the actual label on
  the button
- The instructions include the event type rather than always saying
  "Live Session"
- Clarify that the Internet connection has to be on the user's
  device

### CODE REVIEW

**Comment by sgrimm** [comment]
* **#2948** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2948?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2947** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2947?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @sgrimm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by sgrimm** [comment]
* **#2948** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2948?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2947** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2947?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @sgrimm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by constanzauanini — APPROVED** [review]
Thanks for doing this!

**Comment by sgrimm** [comment]
### Merge activity

* **Aug 2, 4:56 PM EDT**: @sgrimm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-web/2947).

**Pull request merged**
