### PR TITLE
SW-2962 / SW-2963 Sort timezones by display name, use localized facility type in searches

### PR DESCRIPTION
**Pull request by karthikbtf**
- also fix search to use localized facility enum value

### CODE REVIEW

**Review by constanzauanini — APPROVED** [review]
Thanks for fixing this!

**Comment by karthikbtf** [comment]
> Thanks for fixing this!

Thanks for flagging this :) I did not notice it...

**Review by charlie-tf — COMMENTED** [review]
Looks great! Just to make sure I understand: the idea here is that each of these facilities in question is assigned a timezone—either one that is specified by the facility or a default—and that we are sorting them correctly?

**Comment by karthikbtf** [comment]
> Looks great! Just to make sure I understand: the idea here is that each of these facilities in question is assigned a timezone—either one that is specified by the facility or a default—and that we are sorting them correctly?

That is correct. We were rendering them post-sort. 
The render would use the facility's time zone (defaulting to org's time zone if facility doesn't have one). The sort was broken since the data to sort on was missing - and the data being sorted was the id and not the display name.
Moved the display logic into the data population.

**Comment by charlie-tf** [comment]
> > Looks great! Just to make sure I understand: the idea here is that each of these facilities in question is assigned a timezone—either one that is specified by the facility or a default—and that we are sorting them correctly?
> 
> That is correct. We were rendering them post-sort. The render would use the facility's time zone (defaulting to org's time zone if facility doesn't have one). The sort was broken since the data to sort on was missing - and the data being sorted was the id and not the display name. Moved the display logic into the data population.

Got it. Thanks for the explanation!

**Pull request merged**
