### PR TITLE
SW-4839 Implement onUnAssign for projects in the BatchSummary view

### PR DESCRIPTION
**Pull request by nickgraz**

### CODE REVIEW

**Comment by nickgraz** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2157?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #2149** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2149?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #2155** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2155?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #2156** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2156?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #2157** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2157?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-web/2157?utm_source=stack-comment).

**Review by karthikbtf — APPROVED** [review]
Do we need something similar for planting sites?

**Comment by nickgraz** [comment]
Checking that area out now

**Comment by karthikbtf** [comment]
> Checking that area out now

Since I worked on that, I can add this feature there if needed.

**Comment by nickgraz** [comment]
### Merge activity

* **Feb 12, 1:04 PM EST**: @nickgraz started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-web/2157).

**Pull request merged**
